### PR TITLE
Implement game start and restart in the canvas activated by spacebar

### LINKED ISSUE #32: Update game start/end functionality
- Add basic instructions / introductions to canvas before game start.
- Move start game button in to the canvas (can change to press space bar to start or something of that sort)
- Game end functionality should display the score and say Play Again (or something similar)

### PR DESCRIPTION
**Pull request by allindow**
Close #32 
@ryanflach SUCCESS! Your idea to use the event trigger for gameStart led me using the event trigger within gameStart. When gameStart is called, a new Game is "started" but basically only for the purpose of drawing the image to the screen. Once the event handler triggered, it checks an invisible div to see if it's `not-playing` in which case a new game is created, or `playing` in which case it just makes the jeepney jump.

Also... I moved the health hearts to the bottom left under the jeepney. I felt like it was easier to see the changes there during play. But if you hate it, change it back :)

this is going to be so fun when the increasing difficulty is implemented!

### CODE REVIEW

**Comment by ryanflach** [comment]
@allindow Nice job!! 

A few small suggestions - I think when the player goes to the page initially, they should see the instruction screen, regardless of whether or not they have a high score. Also, the last score was showing as 0 for me after each play through?

The health on the bottom is definitely more noticeable. Not sure where I like it most yet. I think if we do keep it on the bottom it should draw from left to right, rather than right to left. What are your thoughts on that?

**Comment by allindow** [comment]
@ryanflach I fixed the high score displaying zero and made the health hearts draw from left to right.

I made it so that on screen load you see the instructions the first time. I believe. That's how it's working for me.

**Comment by ryanflach** [comment]
@allindow I think this looks great. If you're cool with the following suggestions, will you make a few small adjustments?
- Change the health back to the original (I really like it more up in the top right, if that's okay with you). If you don't still have that code handy:

```
Game.prototype.drawHealth = function(context) {
  var x = 825;
  for (var i = 0; i < this.jeepney.health; i++) {
    var img = new Image();
    img.src = 'assets/images/heart.png';
    context.drawImage(img, x, 25, 30, 30);
    x -= 45;
  }
};
```
- Add a margin between the high score text and the canvas - doesn't need to be huge, just feels a little too close right now.
- When the game ends, the text at the top with your score from that round doesn't seem to be centered? Could maybe move down just slightly.

Like I said, all small changes. Let me know if you don't agree with any.

**Comment by allindow** [comment]
@ryanflach I'm not sure what you mean by `doesn't seem to be centered`. I changed it but not sure what you're looking for. Probably just merge if everything looks good and put it where you want if that's not what you meant.

I changed the health back but kind of on the fence about that. For general aesthetics like for a screenshot, I think it looks nice there, but for game play, because the jeepney is not moving except for up and down and the canvas is wide, I think it's way easier for me to watch my score and health when they are all on the side and in the general area of where the focus of the gameplay is. But you probably feel more strongly about it than I do since you asked for that to change back so I went with it!

Added margin.

**Pull request merged**
